@startuml
title Сценарии отказоустойчивости в кластере Docker Swarm

start
:Клиент отправляет запрос на VIP 192.168.56.10;

if (Активный LB жив?) then (да)
  :HAProxy маршрутизирует HTTP на worker-ноды;
else (нет)
  :Keepalived переносит VIP на резервный LB;
  :Резервный HAProxy продолжает маршрутизацию;
endif

if (Выбранный worker жив?) then (да)
  :Запрос попадает в работающую реплику сервиса;
else (нет)
  :HAProxy health check исключает упавший worker;
  :Swarm переразмещает недостающую реплику на оставшихся worker;
endif

if (Живы хотя бы 2 из 3 manager?) then (да)
  :Кворум сохранен;
  :Control plane Swarm остается управляемым;
else (нет)
  :Лидер недоступен;
  :Уже запущенные задачи могут продолжать работу;
  :Операции control plane деградируют;
endif

stop
@enduml
